# Estatística Prática com Python  

## 1. Introdução à Amostragem  

### 📌 Conceito

Amostragem é o processo de selecionar uma parte representativa de uma população para análise estatística. Em vez de analisar todos os elementos (o que pode ser caro ou inviável), escolhemos uma **amostra** para tirar conclusões sobre o todo.

<br>

<img src= "https://solvis.com.br/wp-content/uploads/2021/02/imagem-para-blog-calculadora-de-amostragem-quantas-respostas-precisa-ter-na-pesquisa-solvis-e1613076591189.png" width=500>

Fonte [Solvis](https://solvis.com.br/wp-content/uploads/2021/02/imagem-para-blog-calculadora-de-amostragem-quantas-respostas-precisa-ter-na-pesquisa-solvis-e1613076591189.png)

<br>


- **População ($N$):** conjunto completo de indivíduos, elementos ou eventos.  
- **Amostra ($n$):** subconjunto extraído da população.  

Esse processo deve preservar a **representatividade** da população.

> Exemplo: um banco deseja estimar a média de saldo dos clientes. Em vez de analisar todos os correntistas (população), seleciona 1.000 clientes (amostra) de forma aleatória.

### Importancia da amostragem
<br>

![](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQqOdLxM1gMRp_8wTfxYigAIyA0fen1oS8lmA&s)

<br><br>
### Terminologia sobre Amostragem

<br>

Será necessário definir algumas terminologias normalmente utilizadas quando se fala a respeito de amostragem. Este parâmetros estão descritos a seguir:

- **População**: ou Universo é o conjunto de todas as unidades elementares de interesse. A população deve ser definida claramente e em termos da informação que se pretende conhecer;

<br>

- **Unidade**: trata-se de qualquer elemento da população;

<br>

- **Amostra**: uma parte ou subconjunto da população;

<br>

- **Censo**:  observação de todos os elementos da população;

<br>

- **Parâmetro Populacional**: é o vetor correspondente a todos os valores de uma variável de interesse. Pode ser qualitativa (gosto musical, opnião sobre o governo, etc) ou quantitativa (média, proporção, quantidade, etc).

<br>

- **Função Paramétrica Populacional**:  é uma característica numérica da população, ou seja, uma expressão numérica que condensa os valores do vetor de parâmetro populacional. Por exemplo, média, total, proporção, dentre outros.

<br>



### 🧪 Lab

#### Exemplo 01

In [88]:
from random import sample

alunos = list(range(1, 51))

print(f'População de Alunos: {alunos}')

amostra = sample(alunos, k = 10)

print(f'Amostra da população de alunos: {amostra}')

População de Alunos: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]
Amostra da população de alunos: [13, 29, 8, 11, 37, 5, 27, 12, 10, 24]


#### Exemplo 02

População de N clientes com saldos entre 0 e 100.000 reais.

##### Geração da população

In [112]:
import numpy as np
from numpy import random

N = 1_000_000 # tamanho da população de clientes

np.random.seed(42)
populacao = np.random.uniform(0, 100_000, N)
# 37454.01188474
populacao

array([37454.01188474, 95071.43064099, 73199.39418114, ...,
       41807.19820339, 42867.12566859, 92944.85478505])

In [68]:
print(f'Tamanho da população: {len(populacao)}')

Tamanho da população: 1000000


In [78]:
populacao[50:100]

array([96958.46277646, 77513.28233611, 93949.89415642, 89482.73504276,
       59789.99788111, 92187.42350231,  8849.25020519, 19598.28624191,
        4522.72889105, 32533.03307633, 38867.72896895, 27134.90317739,
       82873.75091519, 35675.33266936, 28093.45096874, 54269.60831582,
       14092.42249748, 80219.6980754 ,  7455.06436798, 98688.69366005,
       77224.47692967, 19871.56815342,   552.21171236, 81546.14284548,
       70685.73438476, 72900.7168041 , 77127.03466859,  7404.46517341,
       35846.57285443, 11586.90595251, 86310.34258756, 62329.81268276,
       33089.80248526,  6355.8350286 , 31098.23217157, 32518.33220267,
       72960.61783381, 63755.74713552, 88721.27425763, 47221.49251619,
       11959.42459383, 71324.4787223 , 76078.50486169, 56127.71975695,
       77096.71799546, 49379.55963644, 52273.2829382 , 42754.10183585,
        2541.91267441, 10789.14269933])

##### Amostragem da população

In [116]:
n = 10_000
amostra = np.random.choice(populacao, size = n, replace=False)
amostra

array([45068.84809321, 31623.42168517, 61042.5487415 , ...,
       74374.37660359, 73994.98078985, 28618.08707979])

In [118]:
print(f'Tamanho da amostra: {len(amostra)}')

Tamanho da amostra: 10000


In [122]:
media_populacional = populacao.mean()
media_amostral = amostra.mean()

print(f'Média populacional: {round(media_populacional, 2)}')
print(f'Média amostral: {round(media_amostral, 2)}')

Média populacional: 50033.45
Média amostral: 50526.12


### Tipos de Amostragem

<br>

Sobre a amostragem, pode-se classicá-la em dois tipos a respeito sobre as probabilidade destas amostra:

<br>

- **Amostra Probabilística**: todos os elementos da população apresentam probabilidade maior que zero de serem selecionados;

<br>

- **Amostra Não-Probabilística**: quando não há probabilidade clara/conhecida de seleção dos elementos. Os elementos são escolhidos de forma julgamental;

<br><br>


---
## 2. Técnicas de Amostragem  

### 2.1 🎯 Amostragem Aleatória Simples

**Conceito:**  
Cada elemento da população tem a **mesma chance** de ser escolhido. É a forma mais básica e intuitiva de amostragem.

> Aplicável quando temos uma lista completa da população ou podemos sortear de forma justa.

#### 🧪 Lab – Psicologia (pesquisa de estresse)

In [182]:
import numpy as np

# Geração da população
populacao = np.random.normal(
    loc = 50,      # média
    scale = 15,    # desvio padrão
    size = 1_000_000  # tamanho da população
)

populacao

array([47.26903986, 32.62326092, 71.06483956, ..., 50.31439463,
       46.72260087, 55.97005552])

In [184]:
# amostragem aleatória simples

amostra1 = np.random.choice(populacao, 10, replace=False)
amostra2 = np.random.choice(populacao, 100, replace=False)
amostra3 = np.random.choice(populacao, 1000, replace=False)
amostra4 = np.random.choice(populacao, 10_000, replace=False)
amostra5 = np.random.choice(populacao, 100_000, replace=False)


In [208]:
print(f'População:  {round(populacao.mean(), 2)}')
print(f'Amostra 01: {round(amostra1.mean() , 2)}')
print(f'Amostra 02: {round(amostra2.mean() , 2)}')
print(f'Amostra 03: {round(amostra3.mean() , 2)}')
print(f'Amostra 04: {round(amostra4.mean() , 2)}')
print(f'Amostra 05: {round(amostra5.mean() , 2)}')

População:  50.0
Amostra 01: 45.32
Amostra 02: 50.52
Amostra 03: 50.09
Amostra 04: 50.1
Amostra 05: 50.02


### 2.2 Amostragem Estratificada  

**Conceito:**  
A população é dividida em **estratos homogêneos** (ex: sexo, idade, faixa de renda), e amostras são selecionadas **proporcionalmente** de cada estrato.

> Garante que todos os grupos relevantes sejam representados.

Procedimento de amostragem:

- Dividir as $N$ unidades da população em $N_1, N_2, \cdots , N_j$ estratos distintos e homogêneos;

- Selecionar, ao acaso, uma amostra de tamanhos $n_1, n_2, \cdots , n_j$ , de modo que o tamanho da amostra seja $n = n_1+n_2+ \cdots +n_j$. O tamanho amostral pode ser proporcional à representatividade do estrato.

<br>

<img src= "https://viacarreira.com/wp-content/uploads/2020/11/amostra-de-pesquisa-2.png" width = 500>

Fonte: [Via Carreira](https://viacarreira.com/wp-content/uploads/2020/11/amostra-de-pesquisa-2.pn)

<br>

### 🧪 Exemplo prático – Saúde (pacientes por faixa etária)

In [30]:
import numpy as np
import pandas as pd

faixas = ["<30","30-60",">60"]
tamanhos = [3000, 5000, 2000]

pressao = [
    np.random.normal(110, 10, tamanhos[0]), # <30
    np.random.normal(110, 12, tamanhos[1]), # 30-60
    np.random.normal(110, 15, tamanhos[2])  # >60  
]

type(pressao)

list

In [32]:
type(pressao[1])

numpy.ndarray

In [34]:
pressao[1].ndim

1

In [36]:
"aula " * 10

'aula aula aula aula aula aula aula aula aula aula '

In [40]:
faixa_etaria = np.concatenate([
    [faixa] * tamanho for faixa, tamanho in zip(faixas, tamanhos)    
])

faixa_etaria

array(['<30', '<30', '<30', ..., '>60', '>60', '>60'], dtype='<U5')

In [52]:
pressao_total = np.concatenate(pressao)

pressao_total

array([120.7792761 , 102.96852659, 104.97755069, ...,  98.34339675,
        88.77128437, 102.29761583])

In [42]:
len(faixa_etaria)

10000

In [48]:
faixa_etaria
pressao

[array([120.7792761 , 102.96852659, 104.97755069, ..., 113.31474983,
        105.26968532, 116.57232311]),
 array([132.69377862, 106.14885449, 129.44828578, ..., 112.89090583,
        105.48549984, 116.10062124]),
 array([108.78187756, 105.87795186,  95.2327133 , ...,  98.34339675,
         88.77128437, 102.29761583])]

In [54]:
df = pd.DataFrame({
    "faixa_etaria": faixa_etaria,
    "pressao": pressao_total
})

df

faixa_etaria     pressao
0             <30  120.779276
1             <30  102.968527
2             <30  104.977551
3             <30  117.896686
4             <30  116.110784
...           ...         ...
9995          >60  113.279630
9996          >60   93.509934
9997          >60   98.343397
9998          >60   88.771284
9999          >60  102.297616

[10000 rows x 2 columns]

In [60]:
df['faixa_etaria'].unique()

array(['<30', '30-60', '>60'], dtype=object)

In [62]:
df['faixa_etaria'].value_counts()

faixa_etaria
30-60    5000
<30      3000
>60      2000
Name: count, dtype: int64

#### Amostra estratificada

In [68]:
amostra_estratificada = df.groupby('faixa_etaria').sample(frac=0.1)
amostra_estratificada

faixa_etaria     pressao
5276        30-60  113.686450
5096        30-60  100.363108
5066        30-60  119.856578
7141        30-60  122.636963
6066        30-60  119.130430
...           ...         ...
8100          >60  116.354243
8520          >60  108.610513
9234          >60   86.217639
8957          >60  103.439075
9158          >60  105.677112

[1000 rows x 2 columns]

#### Amostra estratificada

In [78]:
amostra_estratificada['faixa_etaria'].value_counts()

faixa_etaria
30-60    500
<30      300
>60      200
Name: count, dtype: int64

#### Amostra simples

In [76]:
amostra_simples = df.sample(frac=0.1)
amostra_simples['faixa_etaria'].value_counts()

faixa_etaria
30-60    508
<30      295
>60      197
Name: count, dtype: int64

### 2.3 🔁 Amostragem Sistemática  

**Conceito:**  
Seleciona-se o primeiro elemento aleatoriamente e os próximos em intervalos fixos $k$ (ex: a cada 10 elementos).

Fórmula do intervalo:

$$
k = \frac{N}{n}
$$

> Útil para bases ordenadas: registros médicos, contas bancárias, etc.


### 🧪 Lab

In [102]:
N = 10_000
n = 500
k = N // n

inicio = np.random.randint(0, k)
#                   inicio, fim, passo                    
indices = np.arange(inicio, N,   k) # arange = array + range
print(f'K = {k}')
print(f'Início = {inicio}')
print(f'Índices = {indices[:10]}')

K = 20
Início = 2
Índices = [  2  22  42  62  82 102 122 142 162 182]


### 2.4 🏢 Amostragem por Conglomerado  

**O que é?**  
Ao invés de sortear indivíduos, sorteamos **grupos inteiros** chamados de **conglomerados** (ex: agências bancárias, escolas, bairros, hospitais).

Depois de escolher os conglomerados, **todos os elementos dentro deles são incluídos na amostra**.

**Quando usar?**  
- Quando é difícil acessar a população individualmente.  
- Quando os dados já estão agrupados (ex: registros por agência).  
- Quando o custo para visitar todos os indivíduos é alto.

**Vantagens:**  
- Mais prático e barato.  
- Útil quando os dados estão naturalmente agrupados.

**Desvantagens:**  
- Pode não ser tão representativo quanto a amostragem estratificada.  
- Grupos muito homogêneos podem enviesar os resultados.


#### 🧪 Lab – Pesquisa em clínicas médicas

In [104]:
import numpy as np
import pandas as pd

clinicas = []
for i in range(10):
    clinica_id = f"C_{i+1}"
    pressao = np.random.normal(120+i, 10, 1000)
    clinicas.extend([{"clinica":clinica_id, "pressao": p} for p in pressao])

clinicas

[{'clinica': 'C_1', 'pressao': 130.88753163332967},
 {'clinica': 'C_1', 'pressao': 105.90995590141851},
 {'clinica': 'C_1', 'pressao': 130.62936165790893},
 {'clinica': 'C_1', 'pressao': 109.92495377156783},
 {'clinica': 'C_1', 'pressao': 112.07396466772207},
 {'clinica': 'C_1', 'pressao': 125.62442246237937},
 {'clinica': 'C_1', 'pressao': 115.93510031477028},
 {'clinica': 'C_1', 'pressao': 104.69783504227884},
 {'clinica': 'C_1', 'pressao': 115.82164213208331},
 {'clinica': 'C_1', 'pressao': 145.98820227108473},
 {'clinica': 'C_1', 'pressao': 126.6177830598167},
 {'clinica': 'C_1', 'pressao': 116.74443698813795},
 {'clinica': 'C_1', 'pressao': 125.87639661596148},
 {'clinica': 'C_1', 'pressao': 113.08370963396598},
 {'clinica': 'C_1', 'pressao': 111.19249082289402},
 {'clinica': 'C_1', 'pressao': 119.87379439630608},
 {'clinica': 'C_1', 'pressao': 125.44484242786251},
 {'clinica': 'C_1', 'pressao': 109.83832741459908},
 {'clinica': 'C_1', 'pressao': 124.14766673661367},
 {'clinica': 

In [106]:
df = pd.DataFrame(clinicas)
df

clinica     pressao
0        C_1  130.887532
1        C_1  105.909956
2        C_1  130.629362
3        C_1  109.924954
4        C_1  112.073965
...      ...         ...
9995    C_10  119.956984
9996    C_10  120.426226
9997    C_10  122.587256
9998    C_10  120.551464
9999    C_10  120.999595

[10000 rows x 2 columns]

In [108]:
df['clinica'].value_counts()

clinica
C_1     1000
C_2     1000
C_3     1000
C_4     1000
C_5     1000
C_6     1000
C_7     1000
C_8     1000
C_9     1000
C_10    1000
Name: count, dtype: int64

In [110]:
clinicas_selecionadas = np.random.choice(
    df['clinica'].unique(), 3, replace=False
)

clinicas_selecionadas

array(['C_10', 'C_4', 'C_7'], dtype=object)

In [120]:
df["clinica"].isin(clinicas_selecionadas)

0       False
1       False
2       False
3       False
4       False
        ...  
9995     True
9996     True
9997     True
9998     True
9999     True
Name: clinica, Length: 10000, dtype: bool

In [118]:
type(df)

pandas.core.frame.DataFrame

In [112]:
# selecione no dataframe as clinicas que "estão em (is in) clinicas selecionadas"
amostra = df[df["clinica"].isin(clinicas_selecionadas)]
amostra

clinica     pressao
3000     C_4  136.909749
3001     C_4  116.865231
3002     C_4  115.609476
3003     C_4  112.485530
3004     C_4  121.822402
...      ...         ...
9995    C_10  119.956984
9996    C_10  120.426226
9997    C_10  122.587256
9998    C_10  120.551464
9999    C_10  120.999595

[3000 rows x 2 columns]

In [122]:
print(f'Clínicas sorteadas: {clinicas_selecionadas}')
print(f'Tamanho da amostra: {len(amostra)}')

Clínicas sorteadas: ['C_10' 'C_4' 'C_7']
Tamanho da amostra: 3000


### 3 ⚠️ Viés de Seleção  

Viés acontece quando a amostra **não reflete bem a população**. Pode surgir por:

- Critério de escolha enviesado  
- Falta de grupos importantes  
- Erros de coleta  

> Exemplo: pesquisar apenas usuários de internet exclui idosos que não usam tecnologia.


#### 3.1 📐 Ferramentas úteis para avaliação  

- `seaborn.boxplot()` – compara distribuições  
- `scipy.stats.ttest_ind()` – compara médias  
- `scipy.stats.ks_2samp()` – compara distribuições (teste de Kolmogorov-Smirnov)  