In [ ]:
matriz_A = [[1, 2, 3], [4, 5, 6]]

In [2]:
matriz_A

[(1, 2, 3), (4, 5, 6)]

In [ ]:
matriz_A[0] # ACESSANDO PRIMEIRA LINHA

(1, 2, 3)

In [ ]:
matriz_A[1] # ACESSANDO SEGUNDA LINHA

(4, 5, 6)

In [ ]:
matriz_A[0][1] # ACESSANDO PRIMEIRA LINHA E SEGUNDA COLUNA

2

In [10]:
pip install numpy

   ---------------------------------------- 0.0/12.9 MB ? eta -:--:--
   ------------------------------ --------- 9.7/12.9 MB 51.1 MB/s eta 0:00:01
   ---------------------------------------- 12.9/12.9 MB 47.9 MB/s  0:00:00
Note: you may need to restart the kernel to use updated packages.


  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [ ]:
import numpy as np # MÉTODO ARRAY 

In [12]:
matriz_B = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [14]:
print(matriz_B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
matriz_B[2][1] # TERCEIRA LINHA E SEGUNDA COLUNA

np.int64(8)

In [ ]:
matriz_transposta = matriz_B.transpose() # MÉTODO PARA TRANSPOSIÇÃO DE UMA MATRIZ.

In [17]:
print(matriz_transposta)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [ ]:
matriz1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matriz2 = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])
matriz1 + matriz2 # SOMA DE 2 ARRAYS

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [20]:
matriz3 = np.array([[1, 2], [3, 4], [5, 6]])
matriz4 = np.array([[7, 8, 9], [10, 11, 12]])

In [22]:
print(matriz3)
print(matriz4)

[[1 2]
 [3 4]
 [5 6]]
[[ 7  8  9]
 [10 11 12]]


In [ ]:
np.dot(matriz3, matriz4) ### MÉTODO DOT REALIZA PRODUTO ESCLAR(INTERNO) DE 2 ARRAYS.

array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]])