In [ ]:
### MATRIZ TRANSPOSTA - troca de linhas pelas colunas de uma matriz 

In [4]:
import numpy as np

In [5]:
matriz = np.array([[1, 1, -3], [2, 1, 3], [2, 0, -1]])

In [ ]:
matriz_t = matriz.transpose() # TRANSPONDO A MATRIZ

In [8]:
matriz_t

array([[ 1,  2,  2],
       [ 1,  1,  0],
       [-3,  3, -1]])

In [9]:
matriz.T    

array([[ 1,  2,  2],
       [ 1,  1,  0],
       [-3,  3, -1]])

In [ ]:
### MATRIZ INVERSA - obtida a partir de uma matriz quadrada, tal que o produto entre A e sua inversa (A^-1) resulta na matriz identidade (I).
# Determinante da matriz deve ser !=0
# Matriz deve ser quadrada (Anxn)

In [11]:
A = matriz
A

array([[ 1,  1, -3],
       [ 2,  1,  3],
       [ 2,  0, -1]])

In [ ]:
np.linalg.det(A) ### DETERMINANTE != 0 >>> TEM INVERSA!

np.float64(13.0)

In [16]:
### CALCULANDO A MATRIZ INVERSA

A_inv = np.linalg.inv(A)
A_inv

array([[-0.07692308,  0.07692308,  0.46153846],
       [ 0.61538462,  0.38461538, -0.69230769],
       [-0.15384615,  0.15384615, -0.07692308]])

In [17]:
### CALCULANDO A MATRIZ IDENTIDADE

I = np.dot(A, A_inv)
I

array([[ 1.00000000e+00, -5.55111512e-17,  5.55111512e-17],
       [ 0.00000000e+00,  1.00000000e+00,  5.55111512e-17],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])

In [ ]:
I_3 = np.identity(3) ### MÉTODO 'IDENTITY'
I_3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.eye(10) ### MÉTODO 'EYE'


array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])