In [1]:
!python -m pip install sklearn

  Using cached sklearn-0.0.post12.tar.gz (2.6 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'


  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      The 'sklearn' PyPI package is deprecated, use 'scikit-learn'
      rather than 'sklearn' for pip commands.
      
      Here is how to fix this error in the main use cases:
      - use 'pip install scikit-learn' rather than 'pip install sklearn'
      - replace 'sklearn' by 'scikit-learn' in your pip requirements files
        (requirements.txt, setup.py, setup.cfg, Pipfile, etc ...)
      - if the 'sklearn' package is used by one of your dependencies,
        it would be great if you take some time to track which package uses
        'sklearn' instead of 'scikit-learn' and report it to their issue tracker
      - as a last resort, set the environment variable
        SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True to avoid this error
      
      More information is available at
      https://github.com/scikit-learn/sklearn-

In [2]:
import numpy as np

In [3]:
lista = [1, 2, 3, 4, 5, 6]

array = np.array(lista)

In [4]:
print(type(lista))
print(type(array))

<class 'list'>
<class 'numpy.ndarray'>


In [5]:
arr_zeros = np.zeros(10)

print(arr_zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [6]:
array[0] = 9
print(array)

[9 2 3 4 5 6]


In [7]:
matriz_zeros = np.zeros((5, 3))
print(matriz_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [8]:
## Notas de alunos

lista_de_notas = [9.8, 5.6, 7.8, 9.1, 6.5]

notas = np.array(lista_de_notas)

In [9]:
print("Maximo", notas.max())
print("Minimo", notas.min())
print("Desvio padrao", notas.std())
print("Media", notas.mean())
print("Posicao menor", notas.argmin())


Maximo 9.8
Minimo 5.6
Desvio padrao 1.5628179676469045
Media 7.76
Posicao menor 1


In [10]:
def calcula_notas():
    try:
        notas = (input("Digite as notas dos últimos 10 trabalhos: "))
        lista_notas = [float(n) for n in notas.split()]
        notas_arr = np.array(lista_notas)
    
        if len(notas_arr) == 0:
            return "Nenhuma nota inserida."
    
        return (f"\n---Estatísticas ---"
            f"\nMédia:          {notas_arr.mean():.2f}"
            f"\nDesvio Padrão:  {notas_arr.std():.2f}")
        
    except ValueError:
        return "Erro. Certifique-se de digitar apenas números separados por espaço."

In [11]:
print(calcula_notas())

Nenhuma nota inserida.
