In [11]:
### DETERMINANTES

import numpy as np

matriz = np.array([[1, 2, -3], [2, 1, 3], [2, 0, -1]])

In [12]:
matriz

array([[ 1,  2, -3],
       [ 2,  1,  3],
       [ 2,  0, -1]])

In [13]:
det = np.linalg.det(matriz)

In [14]:
det

np.float64(20.99999999999999)

In [15]:
matriz_a = np.random.randint(0, 10, size=(4, 4))

In [16]:
matriz_a

array([[1, 5, 6, 8],
       [3, 8, 9, 3],
       [9, 0, 4, 3],
       [9, 7, 4, 6]], dtype=int32)

In [17]:
det_a = np.linalg.det(matriz_a)

In [18]:
det_a

np.float64(-3167.999999999998)

In [19]:
matriz_b = np.random.randint(0, 10, size=(3, 4)) # MATRIZ 3 X 4 - NÃO É MATRIZ QUADRADA.

In [20]:
# NÃO SE CALCULA O DETERMINANTE DE UMA MATRIZ QUE NÃO É QUADRADA
# (OU SEJA, TENHA O NÚMERO DE LINHAS DIFERENTE DE COLUNAS)

matriz_b = np.linalg.det(matriz_b)

LinAlgError: Last 2 dimensions of the array must be square

In [27]:
### RESOLVENDO EQUAÇÕES LINEARES NA FORMA MATRICIAL
# Definimos a matriz A e o vetor B
A = np.array([[1, 2, 3], [2, 3, 3], [1, 2, 0]])
B = np.array([1, -3, 6])

In [28]:
A

array([[1, 2, 3],
       [2, 3, 3],
       [1, 2, 0]])

In [29]:
B

array([ 1, -3,  6])

A x = B

x = A_inv * B

In [ ]:
A_inv = np.linalg.inv(A)
A_inv

X = np.linalg.solve(A, B)

###  OU

X = np.dot(A_inv, B)

In [ ]:
X = np.dot(A_inv, B)
X

In [ ]:
X_solve = np.linalg.solve(A, B) # Solução usando linalg.solve
X_solve